create_clock -period 10.000 -name clk_100M -waveform {0.000 5.000} [get_ports clk]

set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN R1  IOSTANDARD LVCMOS33} [get_ports rst]

set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVCMOS33} [get_ports {row[0]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {row[1]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports {row[2]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {row[3]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {col[0]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports {col[1]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports {col[2]}]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports {col[3]}]


set_property PACKAGE_PIN P1  [get_ports encrypt]
set_property PACKAGE_PIN P5  [get_ports decrypt]
set_property PACKAGE_PIN P2  [get_ports ascertain]
set_property PACKAGE_PIN A21 [get_ports locked]
set_property PACKAGE_PIN F21 [get_ports unlocked]
set_property PACKAGE_PIN K17 [get_ports fail_times[2]]
set_property PACKAGE_PIN L13 [get_ports fail_times[1]]
set_property PACKAGE_PIN M13 [get_ports fail_times[0]]
set_property PACKAGE_PIN F15 [get_ports led_ctrl[7]]
set_property PACKAGE_PIN F13 [get_ports led_ctrl[6]]
set_property PACKAGE_PIN F14 [get_ports led_ctrl[5]]
set_property PACKAGE_PIN F16 [get_ports led_ctrl[4]]
set_property PACKAGE_PIN E17 [get_ports led_ctrl[3]]
set_property PACKAGE_PIN C14 [get_ports led_ctrl[2]]
set_property PACKAGE_PIN C15 [get_ports led_ctrl[1]]
set_property PACKAGE_PIN E13 [get_ports led_ctrl[0]]
set_property PACKAGE_PIN A18 [get_ports led_empower[7]]
set_property PACKAGE_PIN A20 [get_ports led_empower[6]]
set_property PACKAGE_PIN B20 [get_ports led_empower[5]]
set_property PACKAGE_PIN E18 [get_ports led_empower[4]]
set_property PACKAGE_PIN F18 [get_ports led_empower[3]]
set_property PACKAGE_PIN D19 [get_ports led_empower[2]]
set_property PACKAGE_PIN E19 [get_ports led_empower[1]]
set_property PACKAGE_PIN C19 [get_ports led_empower[0]]



set_property IOSTANDARD LVCMOS33 [get_ports encrypt]
set_property IOSTANDARD LVCMOS33 [get_ports decrypt]
set_property IOSTANDARD LVCMOS33 [get_ports ascertain]
set_property IOSTANDARD LVCMOS33 [get_ports locked]
set_property IOSTANDARD LVCMOS33 [get_ports unlocked]
set_property IOSTANDARD LVCMOS33 [get_ports fail_times[2]]
set_property IOSTANDARD LVCMOS33 [get_ports fail_times[1]]
set_property IOSTANDARD LVCMOS33 [get_ports fail_times[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_empower[0]]