set_property PACKAGE_PIN R1 [get_ports rst]
set_property PACKAGE_PIN Y9 [get_ports button]
set_property PACKAGE_PIN W4 [get_ports counter]
set_property PACKAGE_PIN Y18 [get_ports clk]

set_property PACKAGE_PIN CA [get_ports led_ca]
set_property PACKAGE_PIN CB [get_ports led_cb]
set_property PACKAGE_PIN CC [get_ports led_cc]
set_property PACKAGE_PIN CD [get_ports led_cd]
set_property PACKAGE_PIN CE [get_ports led_ce]
set_property PACKAGE_PIN CF [get_ports led_cf]
set_property PACKAGE_PIN CG [get_ports led_cg]
set_property PACKAGE_PIN DP [get_ports led_dp]

set_property PACKAGE_PIN A21 [get_ports led[0]]
set_property PACKAGE_PIN E22 [get_ports led[1]]
set_property PACKAGE_PIN D22 [get_ports led[2]]
set_property PACKAGE_PIN E21 [get_ports led[3]]
set_property PACKAGE_PIN D21 [get_ports led[4]]
set_property PACKAGE_PIN G21 [get_ports led[5]]
set_property PACKAGE_PIN G22 [get_ports led[6]]
set_property PACKAGE_PIN F21 [get_ports led[7]]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports counter]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports led_ca]
set_property IOSTANDARD LVCMOS33 [get_ports led_cb]
set_property IOSTANDARD LVCMOS33 [get_ports led_cc]
set_property IOSTANDARD LVCMOS33 [get_ports led_cd]
set_property IOSTANDARD LVCMOS33 [get_ports led_ce]
set_property IOSTANDARD LVCMOS33 [get_ports led_cf]
set_property IOSTANDARD LVCMOS33 [get_ports led_cg]
set_property IOSTANDARD LVCMOS33 [get_ports led_dp]

set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]