set_property PACKAGE_PIN R1   [get_ports clr[0]]
set_property PACKAGE_PIN Y18  [get_ports clk[0]]
set_property PACKAGE_PIN Y9   [get_ports en[0]]
set_property PACKAGE_PIN Y8   [get_ports wsel[0]]
set_property PACKAGE_PIN Y7   [get_ports wsel[1]]
set_property PACKAGE_PIN W9   [get_ports wsel[2]]
set_property PACKAGE_PIN V8   [get_ports rsel[0]]
set_property PACKAGE_PIN AA8  [get_ports rsel[1]]
set_property PACKAGE_PIN AB8  [get_ports rsel[2]]

set_property PACKAGE_PIN W4   [get_ports d[0]]
set_property PACKAGE_PIN R4   [get_ports d[1]]
set_property PACKAGE_PIN T4   [get_ports d[2]]
set_property PACKAGE_PIN T5   [get_ports d[3]]
set_property PACKAGE_PIN U5   [get_ports d[4]]
set_property PACKAGE_PIN W6   [get_ports d[5]]
set_property PACKAGE_PIN W5   [get_ports d[6]]
set_property PACKAGE_PIN U6   [get_ports d[7]]



set_property IOSTANDARD LVCMOS33 [get_ports clr[0]]
set_property IOSTANDARD LVCMOS33 [get_ports clk[0]]
set_property IOSTANDARD LVCMOS33 [get_ports en[0]]

set_property IOSTANDARD LVCMOS33 [get_ports wsel[0]]
set_property IOSTANDARD LVCMOS33 [get_ports wsel[1]]
set_property IOSTANDARD LVCMOS33 [get_ports wsel[2]]
set_property IOSTANDARD LVCMOS33 [get_ports rsel[0]]
set_property IOSTANDARD LVCMOS33 [get_ports rsel[1]]
set_property IOSTANDARD LVCMOS33 [get_ports rsel[2]]

set_property IOSTANDARD LVCMOS33 [get_ports d[0]]
set_property IOSTANDARD LVCMOS33 [get_ports d[1]]
set_property IOSTANDARD LVCMOS33 [get_ports d[2]]
set_property IOSTANDARD LVCMOS33 [get_ports d[3]]
set_property IOSTANDARD LVCMOS33 [get_ports d[4]]
set_property IOSTANDARD LVCMOS33 [get_ports d[5]]
set_property IOSTANDARD LVCMOS33 [get_ports d[6]]
set_property IOSTANDARD LVCMOS33 [get_ports d[7]]